kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-autounseal.fullname" . }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}  
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create 
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-autounseal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}  
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-autounseal.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-autounseal.fullname" . }}
